### ISSUE TITLE
Why is the `sourceDir` option needed?

### ISSUE THREAD

**Issue by m59peacemaker** [per2plex/babel-project-relative-import#8]
It appears to me that the `sourceRoot` option to babel should be used to do what the `sourceDir` option is doing.

Couldn't these two be equivalent?

```
{
  "plugins": [
    ["babel-project-relative-import", {
      "sourceDir": "src/"
    }]
  ]
}
```

``` sh
  babel --source-root src
```

**Comment by m59peacemaker** [comment]
It looks like that option is for something to do with sourcemaps. I can't figure it out.

**Comment by per2plex** [comment]
I think the reason for this option is that some babel wrappers don't allow to set the sourceRoot, but maybe it isn't needed. I'll investigate further as soon as I start refactoring the project to incorporate your ["support require"](https://github.com/per2plex/babel-project-relative-import/pull/7) pull request.

**Comment by per2plex** [comment]
You're right, `sourceRoot` could probably be used instead of the `sourceDir` option. This requires a rewrite though, because `sourceRoot` currently gets joined with the `filename` which also has the source directory in its path. I'll probably have to use the `filenameRelative`, but some babel plugins provide an absolute `filename` so paths have to be resolved correctly. 

Also I don't know how exactly `sourceRoot` interacts with babel internally or other plugins.

I'll leave it for now, but I created an issue (https://github.com/per2plex/babel-project-relative-import/issues/12) for this so I'll probably look into it in the future. If you get/got anymore insight on this matter let me know :)

**Comment by m59peacemaker** [comment]
I think I had the resolving worked out in my plugin, but I approached it a bit differently. Unless there's a good reason not to, I prefer to simply replace `~` with the relative path from the module to the project root, and leave the rest of the path the same. It's easy to reason about.

Consider:

> a/b/1.js
> a/b/2.js

If 2.js requires 1.js:

``` js
require('~/a/b/1.js')
// same as
require('../../../a/b/1.js') 
```

So, that's up for debate.

My tests pass, but when I actually tried to use it, `sourceRoot` didn't do what I expect.

Here's the main function for dealing with the path: 
https://github.com/m59peacemaker/babel-plugin-root-require/blob/81ded8a8e1339717a941da7f00679a998862a1da/index.js#L41

And here is a relevant line I was messing with between commits, but I've just confused myself.
https://github.com/m59peacemaker/babel-plugin-root-require/commit/30fb21c8d506b9e3b474d136d941086e7a7ca434#diff-168726dbe96b3ce427e7fedce31bb0bcL31

**Comment by per2plex** [comment]
Replacing the `~` with the relative path to the project root seems to be a good solution, I'll consider this for the rewrite. Thanks for sharing your thoughts!

Try using `filenameRelative` instead of `filename` in https://github.com/m59peacemaker/babel-plugin-root-require/blob/master/index.js#L55 maybe that will fix your problem.

**Comment by m59peacemaker** [comment]
This plugin now does require and import and in the manner that I was suggesting (simply replace ~ with path to project root). https://github.com/michaelzoidl/babel-root-import

I'm going to ask if the author his thoughts about `sourceRoot`.
